from typing import Any

import reflex as rx


def build_auth_modal(State, CARD_STYLE: dict[str, Any], smartlab_logo) -> rx.Component:
    return rx.cond(
        State.auth_open,
        rx.box(
            rx.box(
                rx.hstack(
                    rx.box(
                        rx.vstack(
                            smartlab_logo("62px"),
                            rx.badge("Acesso Seguro", color_scheme="orange"),
                            rx.heading("Entre na plataforma SmartLab", color="var(--text-primary)", size="7"),
                            rx.text(
                                "Consultores operam clientes, projetos e diagnosticos. O portal do cliente sera liberado com acesso controlado.",
                                color="var(--text-secondary)",
                                font_size="0.96rem",
                            ),
                            rx.vstack(
                                rx.hstack(rx.badge("RBAC", color_scheme="purple"), rx.text("Controle por papel", color="var(--text-muted)")),
                                rx.hstack(rx.badge("Tenant", color_scheme="orange"), rx.text("Dados segregados por cliente", color="var(--text-muted)")),
                                rx.hstack(rx.badge("Local", color_scheme="green"), rx.text("Execucao local com evolucao futura para cloud", color="var(--text-muted)")),
                                align="start",
                                spacing="3",
                                width="100%",
                            ),
                            spacing="4",
                            align="start",
                            width="100%",
                        ),
                        class_name="auth-hero",
                    ),
                    rx.box(
                        rx.vstack(
                            rx.cond(
                                State.force_password_reset_required,
                                rx.vstack(
                                    rx.vstack(
                                        rx.heading("Troca obrigatoria de senha", color="var(--text-primary)", size="6"),
                                        rx.text(
                                            "Este e o primeiro acesso do usuario. Defina uma nova senha para continuar.",
                                            color="var(--text-muted)",
                                        ),
                                        align="start",
                                        spacing="1",
                                        width="100%",
                                    ),
                                    rx.badge("Primeiro acesso", color_scheme="orange"),
                                    rx.vstack(
                                        rx.text("Conta", color="var(--text-muted)", font_size="0.82rem"),
                                        rx.input(
                                            value=State.login_email,
                                            read_only=True,
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        rx.text("Nova senha", color="var(--text-muted)", font_size="0.82rem"),
                                        rx.hstack(
                                            rx.input(
                                                placeholder="Defina a nova senha",
                                                type=rx.cond(State.first_access_password_visible, "text", "password"),
                                                value=State.first_access_new_password,
                                                on_change=State.set_first_access_new_password,
                                                bg="var(--input-bg)",
                                                color="var(--text-primary)",
                                                width="100%",
                                            ),
                                            rx.button(
                                                rx.icon(tag=rx.cond(State.first_access_password_visible, "eye_off", "eye"), size=16),
                                                on_click=State.toggle_first_access_password_visibility,
                                                variant="ghost",
                                                border="1px solid var(--input-border)",
                                            ),
                                            width="100%",
                                        ),
                                        rx.text("Confirmacao", color="var(--text-muted)", font_size="0.82rem"),
                                        rx.hstack(
                                            rx.input(
                                                placeholder="Repita a nova senha",
                                                type=rx.cond(State.first_access_password_visible, "text", "password"),
                                                value=State.first_access_confirm_password,
                                                on_change=State.set_first_access_confirm_password,
                                                bg="var(--input-bg)",
                                                color="var(--text-primary)",
                                                width="100%",
                                            ),
                                            rx.button(
                                                rx.icon(tag=rx.cond(State.first_access_password_visible, "eye_off", "eye"), size=16),
                                                on_click=State.toggle_first_access_password_visibility,
                                                variant="ghost",
                                                border="1px solid var(--input-border)",
                                            ),
                                            width="100%",
                                        ),
                                        rx.button(
                                            "Salvar nova senha",
                                            on_click=State.complete_first_access_password_change,
                                            bg="rgba(255,122,47,0.18)",
                                            color="#fdba74",
                                            border="1px solid rgba(255,122,47,0.38)",
                                            width="100%",
                                            size="3",
                                        ),
                                        width="100%",
                                        align="start",
                                        spacing="2",
                                    ),
                                    spacing="4",
                                    align="start",
                                    width="100%",
                                ),
                                rx.vstack(
                                    rx.vstack(
                                        rx.heading("Acesso", color="var(--text-primary)", size="6"),
                                        rx.text("Login usa uma conta ja existente aprovada pela SmartLab.", color="var(--text-muted)"),
                                        align="start",
                                        spacing="1",
                                        width="100%",
                                    ),
                                    rx.badge("Acesso corporativo", color_scheme="purple"),
                                    rx.vstack(
                                        rx.text("E-mail", color="var(--text-muted)", font_size="0.82rem"),
                                        rx.input(
                                            placeholder="admin@smartlab.com",
                                            value=State.login_email,
                                            on_change=State.set_login_email,
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        rx.text("Senha", color="var(--text-muted)", font_size="0.82rem"),
                                        rx.hstack(
                                            rx.input(
                                                placeholder="Digite sua senha",
                                                type=rx.cond(State.login_password_visible, "text", "password"),
                                                value=State.login_password,
                                                on_change=State.set_login_password,
                                                bg="var(--input-bg)",
                                                color="var(--text-primary)",
                                                width="100%",
                                            ),
                                            rx.button(
                                                rx.icon(tag=rx.cond(State.login_password_visible, "eye_off", "eye"), size=16),
                                                on_click=State.toggle_login_password_visibility,
                                                variant="ghost",
                                                border="1px solid var(--input-border)",
                                            ),
                                            width="100%",
                                        ),
                                        rx.button(
                                            "Entrar no workspace",
                                            on_click=State.login,
                                            bg="rgba(255,122,47,0.18)",
                                            color="#fdba74",
                                            border="1px solid rgba(255,122,47,0.38)",
                                            width="100%",
                                            size="3",
                                        ),
                                        rx.box(
                                            rx.vstack(
                                                rx.text("Como o acesso funciona", color="var(--text-primary)", font_weight="700"),
                                                rx.text("1. A SmartLab cria ou libera sua conta.", color="var(--text-muted)", font_size="0.84rem"),
                                                rx.text("2. Voce entra com credenciais ja existentes.", color="var(--text-muted)", font_size="0.84rem"),
                                                rx.text("3. O que voce enxerga depende do tenant e do seu papel.", color="var(--text-muted)", font_size="0.84rem"),
                                                align="start",
                                                spacing="1",
                                                width="100%",
                                            ),
                                            class_name="auth-note",
                                        ),
                                        rx.hstack(
                                            rx.text("Nao existe auto-registro publico nesta fase.", color="var(--text-muted)", font_size="0.82rem"),
                                            rx.spacer(),
                                            rx.text("Provisionamento controlado", color="var(--text-muted)", font_size="0.82rem"),
                                            width="100%",
                                        ),
                                        width="100%",
                                        align="start",
                                        spacing="2",
                                    ),
                                    spacing="4",
                                    align="start",
                                    width="100%",
                                ),
                            ),
                            rx.hstack(
                                rx.button("Fechar", on_click=State.close_auth, variant="ghost", color="var(--text-muted)"),
                                rx.spacer(),
                                rx.text("Desenvolvido por i9Exp - SmartLab", color="var(--text-muted)", font_size="0.82rem"),
                                width="100%",
                            ),
                            spacing="4",
                            align="start",
                            width="100%",
                        ),
                        class_name="auth-panel",
                    ),
                    width="min(1080px, 92vw)",
                    align="stretch",
                    spacing="5",
                ),
                width="min(1120px, 94vw)",
                padding="1.2rem",
                spacing="0",
                **CARD_STYLE,
                class_name="auth-shell",
            ),
            position="fixed",
            inset="0",
            bg="var(--overlay-bg)",
            display="flex",
            align_items="center",
            justify_content="center",
            z_index="1000",
        ),
        rx.fragment(),
    )
