from typing import Any

import reflex as rx


def build_projetos_view(
    State,
    CARD_STYLE: dict[str, Any],
    workflow_node,
    workflow_connection_line,
    pesquisa_builder_view,
) -> rx.Component:
    workflow_builder_panel = rx.box(
        rx.vstack(
            rx.heading("Builder de Workflow", color="var(--text-primary)", size="5"),
            rx.text(
                "Use esta aba para desenhar a jornada operacional do projeto, automatizações, checklists e entregáveis.",
                color="var(--text-muted)",
            ),
            rx.hstack(
                rx.input(
                    placeholder="Título da caixa (ex: Visita Técnica)",
                    value=State.new_box_title,
                    on_change=State.set_new_box_title,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                ),
                rx.select(
                    ["trigger", "etapa", "coleta", "analise", "relatorio"],
                    value=State.new_box_type,
                    on_change=State.set_new_box_type,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="140px",
                ),
                rx.button(
                    "Adicionar Caixa",
                    on_click=State.add_workflow_box,
                    bg="rgba(255,122,47,0.18)",
                    color="#fdba74",
                    border="1px solid rgba(255,122,47,0.38)",
                ),
                width="100%",
                spacing="3",
                flex_wrap="wrap",
            ),
            rx.grid(
                rx.input(
                    placeholder="String Input: endpoint/URL do node",
                    value=State.new_box_endpoint,
                    on_change=State.set_new_box_endpoint,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.select(
                    ["GET", "POST", "PUT", "DELETE"],
                    value=State.new_box_method,
                    on_change=State.set_new_box_method,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.text_area(
                    placeholder="Collection Input: headers separados por vírgula",
                    value=State.new_box_headers,
                    on_change=State.set_new_box_headers,
                    min_height="84px",
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.select(
                    ["none", "simple", "exponential"],
                    value=State.new_box_retry_policy,
                    on_change=State.set_new_box_retry_policy,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.input(
                    placeholder="Fixed Collection: client_id",
                    value=State.new_box_client_id,
                    on_change=State.set_new_box_client_id,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.input(
                    placeholder="Fixed Collection: client_secret",
                    value=State.new_box_client_secret,
                    on_change=State.set_new_box_client_secret,
                    type="password",
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.input(
                    placeholder="Trigger schedule (cron)",
                    value=State.new_box_schedule,
                    on_change=State.set_new_box_schedule,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.select(
                    ["left", "center", "right"],
                    value=State.new_box_zone,
                    on_change=State.set_new_box_zone,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.input(
                    placeholder="Condicao de execucao (ex: score < 3)",
                    value=State.new_box_condition,
                    on_change=State.set_new_box_condition,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.input(
                    placeholder="Chave de saida (ex: diagnostico.score)",
                    value=State.new_box_output_key,
                    on_change=State.set_new_box_output_key,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                columns="2",
                spacing="3",
                width="100%",
            ),
            rx.hstack(
                rx.input(
                    placeholder="Sticky Note no canvas",
                    value=State.new_sticky_note_text,
                    on_change=State.set_new_sticky_note_text,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.button(
                    "Adicionar Sticky Note",
                    on_click=State.add_sticky_note,
                    bg="rgba(255,122,47,0.18)",
                    color="#fdba74",
                    border="1px solid rgba(255,122,47,0.38)",
                ),
                width="100%",
                spacing="3",
            ),
            rx.hstack(
                rx.button(
                    "Execute Workflow",
                    on_click=State.execute_workflow,
                    bg="rgba(255,122,47,0.18)",
                    color="#fdba74",
                    border="1px solid rgba(255,122,47,0.38)",
                ),
                rx.button(
                    "Limpar logs",
                    on_click=State.clear_workflow_logs,
                    variant="ghost",
                    border="1px solid var(--input-border)",
                    color="var(--text-secondary)",
                ),
                width="100%",
                spacing="3",
            ),
            rx.box(
                rx.vstack(
                    rx.text("Canvas", color="var(--text-primary)", font_weight="700"),
                    rx.foreach(
                        State.workflow_canvas_items,
                        lambda item: rx.vstack(
                            workflow_node(item),
                            rx.cond(item["has_next"], workflow_connection_line(item["line_type"]), rx.fragment()),
                            width="100%",
                            align="center",
                            spacing="1",
                        ),
                    ),
                    width="100%",
                    spacing="1",
                    align="center",
                ),
                class_name="workflow-canvas",
                width="100%",
            ),
            rx.box(
                rx.vstack(
                    rx.text("Blueprint do fluxo", color="var(--text-primary)", font_weight="700"),
                    rx.foreach(
                        State.workflow_blueprint,
                        lambda row: rx.box(
                            rx.hstack(
                                rx.text(row["title"], color="var(--text-primary)", width="100%"),
                                rx.badge(row["type"], color_scheme="purple"),
                                rx.text(row["condition"], color="var(--text-secondary)", width="100%"),
                                rx.text(row["output"], color="var(--accent-strong)", width="100%"),
                                width="100%",
                                align="center",
                            ),
                            width="100%",
                            padding="0.65rem 0.8rem",
                            border="1px solid var(--input-border)",
                            border_radius="12px",
                            bg="var(--surface-soft)",
                        ),
                    ),
                    width="100%",
                    spacing="2",
                    align="start",
                ),
                class_name="workflow-logs",
                width="100%",
            ),
            rx.box(
                rx.vstack(
                    rx.text("Logs de execução", color="var(--text-primary)", font_weight="700"),
                    rx.foreach(
                        State.workflow_logs,
                        lambda line: rx.text(line, color="var(--text-secondary)", font_size="0.78rem"),
                    ),
                    width="100%",
                    spacing="1",
                    align="start",
                ),
                class_name="workflow-logs",
                width="100%",
            ),
            align="start",
            width="100%",
            spacing="3",
        ),
        padding="1rem",
        width="100%",
        min_width="100%",
        **CARD_STYLE,
    )

    return rx.vstack(
        rx.cond(
            State.can_configure_projects,
            rx.vstack(
                rx.box(
                    rx.vstack(
                        rx.hstack(
                            rx.heading("Projetos SmartLab - interno", color="var(--text-primary)", size="5"),
                            rx.spacer(),
                            rx.hstack(
                                rx.foreach(
                                    State.project_admin_tabs,
                                    lambda tab: rx.button(
                                        rx.cond(
                                            tab == "cadastro",
                                            "Cadastro",
                                            "Workflow",
                                        ),
                                        on_click=State.set_project_admin_tab(tab),
                                        bg=rx.cond(
                                            State.project_admin_tab == tab,
                                            "rgba(255,122,47,0.18)",
                                            "transparent",
                                        ),
                                        color=rx.cond(
                                            State.project_admin_tab == tab,
                                            "#fdba74",
                                            "var(--text-secondary)",
                                        ),
                                        border=rx.cond(
                                            State.project_admin_tab == tab,
                                            "1px solid rgba(255,122,47,0.38)",
                                            "1px solid var(--input-border)",
                                        ),
                                        size="2",
                                        width="100%",
                                        flex="1",
                                        justify_content="center",
                                    ),
                                ),
                                spacing="2",
                                width="100%",
                            ),
                            width="100%",
                            align="center",
                        ),
                        rx.box(
                            rx.cond(
                                State.project_admin_tab == "cadastro",
                                rx.vstack(
                                    rx.box(
                                        rx.vstack(
                                            rx.heading("Cadastro da Survey", color="var(--text-primary)", size="4"),
                                            rx.text(
                                                "Defina o serviço SmartLab, nome da pesquisa, dimensões e perguntas. Tudo fica vinculado à survey criada nesta aba.",
                                                color="var(--text-muted)",
                                            ),
                                            rx.hstack(
                                                rx.badge("Serviço SmartLab", color_scheme="orange"),
                                                rx.badge("Survey", color_scheme="purple"),
                                                rx.badge("Dimensões e Perguntas", color_scheme="gray"),
                                                spacing="2",
                                                width="100%",
                                                flex_wrap="wrap",
                                            ),
                                            align="start",
                                            width="100%",
                                            spacing="3",
                                        ),
                                        padding="1rem",
                                        width="100%",
                                        **CARD_STYLE,
                                    ),
                                    pesquisa_builder_view(),
                                    width="100%",
                                    min_width="100%",
                                    spacing="4",
                                ),
                                rx.vstack(
                                    rx.select(
                                        State.project_id_options,
                                        value=State.selected_project_option,
                                        on_change=State.select_project,
                                        placeholder="Selecione projeto",
                                        bg="var(--input-bg)",
                                        color="var(--text-primary)",
                                        width="100%",
                                    ),
                                    workflow_builder_panel,
                                    width="100%",
                                    min_width="100%",
                                    spacing="4",
                                ),
                            ),
                            width="100%",
                            min_width="100%",
                            min_height="620px",
                        ),
                        width="100%",
                        min_width="100%",
                        spacing="3",
                        align="stretch",
                    ),
                    padding="1rem",
                    **CARD_STYLE,
                    width="100%",
                    min_width="100%",
                ),
                width="100%",
                min_width="100%",
                spacing="4",
                align="stretch",
            ),
            rx.box(
                rx.vstack(
                    rx.heading("Acesso restrito", color="var(--text-primary)", size="5"),
                    rx.text(
                        "A tela de Projetos e exclusiva do SmartLab - interno. Outros tenants nao acessam criacao, configuracao ou vinculacao de projetos.",
                        color="var(--text-muted)",
                    ),
                    align="start",
                    width="100%",
                    spacing="3",
                ),
                width="100%",
                padding="1rem",
                **CARD_STYLE,
            ),
        ),
        width="100%",
        spacing="4",
    )
