from typing import Any

import reflex as rx


def build_projetos_view(
    State,
    CARD_STYLE: dict[str, Any],
    custom_option_field,
    workflow_node,
    workflow_connection_line,
    pesquisa_builder_view,
) -> rx.Component:
    project_portfolio_panel = rx.vstack(
        rx.box(
            rx.vstack(
                rx.heading("Projeto Contratado", color="var(--text-primary)", size="4"),
                rx.text(
                    "Registre aqui qual serviço a SmartLab irá ofertar, para qual cliente e em que data o contrato entrou em execução.",
                    color="var(--text-muted)",
                ),
                rx.grid(
                    rx.input(
                        placeholder="Nome interno do projeto",
                        value=State.new_project_name,
                        on_change=State.set_new_project_name,
                        bg="var(--input-bg)",
                        color="var(--text-primary)",
                        width="100%",
                    ),
                    rx.select(
                        State.smartlab_service_options,
                        value=State.new_project_service_name,
                        on_change=State.set_new_project_service_name,
                        bg="var(--input-bg)",
                        color="var(--text-primary)",
                        width="100%",
                    ),
                    rx.cond(
                        State.new_project_service_name == "Outro",
                        custom_option_field(
                            "Novo Serviço SmartLab",
                            value=State.new_project_custom_service_name,
                            on_change=State.set_new_project_custom_service_name,
                            on_confirm=State.confirm_new_project_service_name,
                            placeholder="Digite aqui para cadastrar um novo serviço",
                            help_text="Clique em OK para registrar o serviço e trazê-lo de volta ao seletor.",
                        ),
                        rx.fragment(),
                    ),
                    rx.select(
                        State.project_client_options,
                        value=State.selected_project_client_option,
                        on_change=State.set_new_project_client_option,
                        placeholder="Cliente contratante",
                        bg="var(--input-bg)",
                        color="var(--text-primary)",
                        width="100%",
                    ),
                    rx.input(
                        type="date",
                        value=State.new_project_contracted_at,
                        on_change=State.set_new_project_contracted_at,
                        bg="var(--input-bg)",
                        color="var(--text-primary)",
                        width="100%",
                    ),
                    columns="2",
                    spacing="3",
                    width="100%",
                ),
                rx.button("Registrar Projeto", on_click=State.create_project, class_name="primary-soft-action"),
                align="start",
                spacing="3",
                width="100%",
            ),
            padding="1rem",
            width="100%",
            **CARD_STYLE,
        ),
        rx.box(
            rx.vstack(
                rx.hstack(
                    rx.heading("Portfólio de Projetos", color="var(--text-primary)", size="4"),
                    rx.spacer(),
                    rx.badge(State.selected_project_record["service_name"], color_scheme="purple"),
                    width="100%",
                ),
                rx.vstack(
                    rx.hstack(
                        rx.text("Todos os projetos", color="var(--text-primary)", font_weight="700"),
                        rx.spacer(),
                        rx.select(
                            State.project_portfolio_service_options,
                            value=State.project_portfolio_service_filter,
                            on_change=State.set_project_portfolio_service_filter,
                            bg="var(--input-bg)",
                            color="var(--text-primary)",
                            width="260px",
                        ),
                        rx.badge(f"{State.filtered_projects_data.length()} registros", color_scheme="gray", variant="soft"),
                        width="100%",
                        align="center",
                        spacing="3",
                    ),
                    rx.cond(
                        State.filtered_projects_data.length() == 0,
                        rx.box(
                            rx.text(
                                "Nenhum projeto encontrado para o serviço selecionado.",
                                color="var(--text-muted)",
                                font_size="0.86rem",
                            ),
                            width="100%",
                            padding="0.9rem 1rem",
                            border="1px dashed var(--input-border)",
                            border_radius="14px",
                            bg="var(--surface-soft)",
                        ),
                        rx.vstack(
                            rx.grid(
                                rx.text("ID", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", text_align="center", width="100%"),
                                rx.text("Projeto", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Serviço", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Cliente", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Data", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Entrevistas", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Status", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Ações", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", text_align="center", width="100%"),
                                grid_template_columns="60px minmax(220px,1.6fr) minmax(170px,1.15fr) minmax(140px,0.95fr) 118px 116px 110px minmax(220px,1.25fr)",
                                width="100%",
                                align_items="center",
                                justify_items="stretch",
                                padding="0.1rem 0 0.85rem",
                                border_bottom="1px solid rgba(148,163,184,0.18)",
                                column_gap="0.9rem",
                            ),
                            rx.foreach(
                                State.filtered_projects_data,
                                lambda item: rx.grid(
                                    rx.box(
                                        rx.text(item["id"], color="var(--text-primary)", font_weight="600", font_size="0.85rem"),
                                        width="100%",
                                        text_align="center",
                                    ),
                                    rx.cond(
                                        State.editing_project_id == item["id"].to_string(),
                                        rx.input(
                                            value=State.new_project_name,
                                            on_change=State.set_new_project_name,
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        rx.button(
                                            rx.text(item["name"], color="var(--text-primary)", font_weight="600"),
                                            on_click=State.select_project(f'{item["id"]} - {item["name"]}'),
                                            width="100%",
                                            justify_content="flex-start",
                                            text_align="left",
                                            bg="transparent",
                                            border="0",
                                            padding="0",
                                        ),
                                    ),
                                    rx.cond(
                                        State.editing_project_id == item["id"].to_string(),
                                        rx.select(
                                            State.smartlab_service_options,
                                            value=State.new_project_service_name,
                                            on_change=State.set_new_project_service_name,
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        rx.text(item["service_name"], color="var(--text-secondary)", font_size="0.82rem"),
                                    ),
                                    rx.cond(
                                        State.editing_project_id == item["id"].to_string(),
                                        rx.select(
                                            State.project_client_options,
                                            value=State.selected_project_client_option,
                                            on_change=State.set_new_project_client_option,
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        rx.text(item["client_name"], color="var(--text-secondary)", font_size="0.82rem"),
                                    ),
                                    rx.cond(
                                        State.editing_project_id == item["id"].to_string(),
                                        rx.input(
                                            type="date",
                                            value=State.new_project_contracted_at,
                                            on_change=State.set_new_project_contracted_at,
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        rx.text(item["contracted_at"], color="var(--text-secondary)", font_size="0.82rem"),
                                    ),
                                    rx.vstack(
                                        rx.text(item["interview_count"], color="var(--text-primary)", font_weight="600", font_size="0.83rem"),
                                        rx.text(
                                            f'Ações {item["action_count"]} • Workflow {item["workflow_count"]} • IA {item["knowledge_count"]}',
                                            color="var(--text-muted)",
                                            font_size="0.74rem",
                                            width="100%",
                                            white_space="normal",
                                            word_break="break-word",
                                        ),
                                        spacing="0",
                                        align="start",
                                        width="100%",
                                    ),
                                    rx.badge(item["status"], color_scheme="purple", variant="soft"),
                                    rx.cond(
                                        State.editing_project_id == item["id"].to_string(),
                                        rx.hstack(
                                            rx.button(
                                                "Salvar",
                                                on_click=State.save_project_inline,
                                                bg="rgba(34,197,94,0.16)",
                                                color="#86efac",
                                                border="1px solid rgba(34,197,94,0.34)",
                                                size="1",
                                            ),
                                            rx.button(
                                                "Cancelar",
                                                on_click=State.cancel_edit_project,
                                                bg="rgba(250,204,21,0.16)",
                                                color="#fde68a",
                                                border="1px solid rgba(250,204,21,0.34)",
                                                size="1",
                                            ),
                                            spacing="2",
                                            justify="center",
                                            width="100%",
                                        ),
                                        rx.hstack(
                                            rx.button(
                                                "Alterar",
                                                on_click=State.start_edit_project(item["id"]),
                                                bg="rgba(255,122,47,0.18)",
                                                color="#fdba74",
                                                border="1px solid rgba(255,122,47,0.38)",
                                                size="1",
                                            ),
                                            rx.button(
                                                "Excluir",
                                                on_click=State.request_delete_confirmation(
                                                    "project",
                                                    item["id"],
                                                    f'{item["name"]} | entrevistas {item["interview_count"]} | ações {item["action_count"]} | workflow {item["workflow_count"]} | IA {item["knowledge_count"]}',
                                                ),
                                                bg="rgba(239,68,68,0.2)",
                                                color="#fca5a5",
                                                border="1px solid rgba(239,68,68,0.4)",
                                                size="1",
                                            ),
                                            spacing="2",
                                            justify="center",
                                            width="100%",
                                        ),
                                    ),
                                    grid_template_columns="60px minmax(220px,1.6fr) minmax(170px,1.15fr) minmax(140px,0.95fr) 118px 116px 110px minmax(220px,1.25fr)",
                                    width="100%",
                                    align_items="center",
                                    justify_items="stretch",
                                    column_gap="0.9rem",
                                    padding="0.55rem 0",
                                    border_bottom="1px solid rgba(148,163,184,0.12)",
                                ),
                            ),
                            width="100%",
                            spacing="0",
                            align="stretch",
                        ),
                    ),
                    width="100%",
                    spacing="2",
                    align="start",
                ),
                align="start",
                spacing="3",
                width="100%",
            ),
            padding="1rem",
            width="100%",
            **CARD_STYLE,
        ),
        width="100%",
        spacing="4",
    )

    workflow_builder_panel = rx.box(
        rx.vstack(
            rx.heading("Builder de Workflow", color="var(--text-primary)", size="5"),
            rx.text(
                "Use esta aba para desenhar a jornada operacional do projeto. A estrutura abaixo já resume o que existe no banco para grupo, empresa, áreas, usuários e reportes.",
                color="var(--text-muted)",
            ),
            rx.grid(
                rx.foreach(
                    State.workflow_hierarchy_snapshot,
                    lambda item: rx.box(
                        rx.vstack(
                            rx.text(item["label"], color="var(--text-muted)", font_size="0.78rem"),
                            rx.text(item["value"], color="var(--text-primary)", font_weight="700"),
                            rx.text(item["detail"], color="var(--text-secondary)", font_size="0.8rem"),
                            align="start",
                            spacing="1",
                            width="100%",
                        ),
                        padding="0.8rem",
                        class_name="panel-card metric-card",
                        **CARD_STYLE,
                    ),
                ),
                columns="5",
                spacing="3",
                width="100%",
            ),
            rx.hstack(
                rx.input(
                    placeholder="Título da caixa (ex: Visita Técnica)",
                    value=State.new_box_title,
                    on_change=State.set_new_box_title,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                ),
                rx.select(
                    ["trigger", "etapa", "coleta", "analise", "relatorio"],
                    value=State.new_box_type,
                    on_change=State.set_new_box_type,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="140px",
                ),
                rx.button(
                    "Adicionar Caixa",
                    on_click=State.add_workflow_box,
                    bg="rgba(255,122,47,0.18)",
                    color="#fdba74",
                    border="1px solid rgba(255,122,47,0.38)",
                ),
                width="100%",
                spacing="3",
                flex_wrap="wrap",
            ),
            rx.grid(
                rx.input(
                    placeholder="String Input: endpoint/URL do node",
                    value=State.new_box_endpoint,
                    on_change=State.set_new_box_endpoint,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.select(
                    ["GET", "POST", "PUT", "DELETE"],
                    value=State.new_box_method,
                    on_change=State.set_new_box_method,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.text_area(
                    placeholder="Collection Input: headers separados por vírgula",
                    value=State.new_box_headers,
                    on_change=State.set_new_box_headers,
                    min_height="84px",
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.select(
                    ["none", "simple", "exponential"],
                    value=State.new_box_retry_policy,
                    on_change=State.set_new_box_retry_policy,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.input(
                    placeholder="Fixed Collection: client_id",
                    value=State.new_box_client_id,
                    on_change=State.set_new_box_client_id,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.input(
                    placeholder="Fixed Collection: client_secret",
                    value=State.new_box_client_secret,
                    on_change=State.set_new_box_client_secret,
                    type="password",
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.input(
                    placeholder="Trigger schedule (cron)",
                    value=State.new_box_schedule,
                    on_change=State.set_new_box_schedule,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.select(
                    ["left", "center", "right"],
                    value=State.new_box_zone,
                    on_change=State.set_new_box_zone,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.input(
                    placeholder="Condicao de execucao (ex: score < 3)",
                    value=State.new_box_condition,
                    on_change=State.set_new_box_condition,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.input(
                    placeholder="Chave de saida (ex: diagnostico.score)",
                    value=State.new_box_output_key,
                    on_change=State.set_new_box_output_key,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                columns="2",
                spacing="3",
                width="100%",
            ),
            rx.hstack(
                rx.input(
                    placeholder="Sticky Note no canvas",
                    value=State.new_sticky_note_text,
                    on_change=State.set_new_sticky_note_text,
                    bg="var(--input-bg)",
                    color="var(--text-primary)",
                    width="100%",
                ),
                rx.button(
                    "Adicionar Sticky Note",
                    on_click=State.add_sticky_note,
                    bg="rgba(255,122,47,0.18)",
                    color="#fdba74",
                    border="1px solid rgba(255,122,47,0.38)",
                ),
                width="100%",
                spacing="3",
            ),
            rx.hstack(
                rx.button(
                    "Execute Workflow",
                    on_click=State.execute_workflow,
                    bg="rgba(255,122,47,0.18)",
                    color="#fdba74",
                    border="1px solid rgba(255,122,47,0.38)",
                ),
                rx.button(
                    "Limpar logs",
                    on_click=State.clear_workflow_logs,
                    variant="ghost",
                    border="1px solid var(--input-border)",
                    color="var(--text-secondary)",
                ),
                width="100%",
                spacing="3",
            ),
            rx.box(
                rx.vstack(
                    rx.text("Canvas", color="var(--text-primary)", font_weight="700"),
                    rx.foreach(
                        State.workflow_canvas_items,
                        lambda item: rx.vstack(
                            workflow_node(item),
                            rx.cond(item["has_next"], workflow_connection_line(item["line_type"]), rx.fragment()),
                            width="100%",
                            align="center",
                            spacing="1",
                        ),
                    ),
                    width="100%",
                    spacing="1",
                    align="center",
                ),
                class_name="workflow-canvas",
                width="100%",
            ),
            rx.box(
                rx.vstack(
                    rx.text("Blueprint do fluxo", color="var(--text-primary)", font_weight="700"),
                    rx.foreach(
                        State.workflow_blueprint,
                        lambda row: rx.box(
                            rx.hstack(
                                rx.text(row["title"], color="var(--text-primary)", width="100%"),
                                rx.badge(row["type"], color_scheme="purple"),
                                rx.text(row["condition"], color="var(--text-secondary)", width="100%"),
                                rx.text(row["output"], color="var(--accent-strong)", width="100%"),
                                width="100%",
                                align="center",
                            ),
                            width="100%",
                            padding="0.65rem 0.8rem",
                            border="1px solid var(--input-border)",
                            border_radius="12px",
                            bg="var(--surface-soft)",
                        ),
                    ),
                    width="100%",
                    spacing="2",
                    align="start",
                ),
                class_name="workflow-logs",
                width="100%",
            ),
            rx.box(
                rx.vstack(
                    rx.text("Logs de execução", color="var(--text-primary)", font_weight="700"),
                    rx.foreach(
                        State.workflow_logs,
                        lambda line: rx.text(line, color="var(--text-secondary)", font_size="0.78rem"),
                    ),
                    width="100%",
                    spacing="1",
                    align="start",
                ),
                class_name="workflow-logs",
                width="100%",
            ),
            align="start",
            width="100%",
            spacing="3",
        ),
        padding="1rem",
        width="100%",
        min_width="100%",
        **CARD_STYLE,
    )

    return rx.vstack(
        rx.cond(
            State.can_configure_projects,
            rx.vstack(
                rx.box(
                    rx.vstack(
                        rx.hstack(
                            rx.heading("Projetos SmartLab - interno", color="var(--text-primary)", size="5"),
                            rx.spacer(),
                            rx.hstack(
                                rx.foreach(
                                    State.project_admin_tabs,
                                    lambda tab: rx.button(
                                        rx.cond(
                                            tab == "cadastro",
                                            "Cadastro",
                                            rx.cond(tab == "projetos", "Projetos", "Workflow"),
                                        ),
                                        on_click=State.set_project_admin_tab(tab),
                                        bg=rx.cond(
                                            State.project_admin_tab == tab,
                                            "rgba(255,122,47,0.18)",
                                            "transparent",
                                        ),
                                        color=rx.cond(
                                            State.project_admin_tab == tab,
                                            "#fdba74",
                                            "var(--text-secondary)",
                                        ),
                                        border=rx.cond(
                                            State.project_admin_tab == tab,
                                            "1px solid rgba(255,122,47,0.38)",
                                            "1px solid var(--input-border)",
                                        ),
                                        size="2",
                                        width="100%",
                                        flex="1",
                                        justify_content="center",
                                    ),
                                ),
                                spacing="2",
                                width="100%",
                            ),
                            width="100%",
                            align="center",
                        ),
                        rx.box(
                            rx.cond(
                                State.project_admin_tab == "cadastro",
                                rx.vstack(
                                    rx.box(
                                        rx.vstack(
                                            rx.heading("Cadastro da Survey", color="var(--text-primary)", size="4"),
                                            rx.text(
                                                "Defina o serviço SmartLab, nome da pesquisa, dimensões e perguntas. Tudo fica vinculado à survey criada nesta aba.",
                                                color="var(--text-muted)",
                                            ),
                                            rx.hstack(
                                                rx.badge("Serviço SmartLab", color_scheme="orange"),
                                                rx.badge("Survey", color_scheme="purple"),
                                                rx.badge("Dimensões e Perguntas", color_scheme="gray"),
                                                spacing="2",
                                                width="100%",
                                                flex_wrap="wrap",
                                            ),
                                            align="start",
                                            width="100%",
                                            spacing="3",
                                        ),
                                        padding="1rem",
                                        width="100%",
                                        **CARD_STYLE,
                                    ),
                                    pesquisa_builder_view(),
                                    width="100%",
                                    min_width="100%",
                                    spacing="4",
                                ),
                                rx.cond(
                                    State.project_admin_tab == "projetos",
                                    project_portfolio_panel,
                                    rx.vstack(
                                        rx.select(
                                            State.project_id_options,
                                            value=State.selected_project_option,
                                            on_change=State.select_project,
                                            placeholder="Selecione projeto",
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        workflow_builder_panel,
                                        width="100%",
                                        min_width="100%",
                                        spacing="4",
                                    ),
                                ),
                            ),
                            width="100%",
                            min_width="100%",
                            min_height="620px",
                        ),
                        width="100%",
                        min_width="100%",
                        spacing="3",
                        align="stretch",
                    ),
                    padding="1rem",
                    **CARD_STYLE,
                    width="100%",
                    min_width="100%",
                ),
                width="100%",
                min_width="100%",
                spacing="4",
                align="stretch",
            ),
            rx.box(
                rx.vstack(
                    rx.heading("Acesso restrito", color="var(--text-primary)", size="5"),
                    rx.text(
                        "A tela de Projetos e exclusiva do SmartLab - interno. Outros tenants nao acessam criacao, configuracao ou vinculacao de projetos.",
                        color="var(--text-muted)",
                    ),
                    align="start",
                    width="100%",
                    spacing="3",
                ),
                width="100%",
                padding="1rem",
                **CARD_STYLE,
            ),
        ),
        width="100%",
        spacing="4",
    )
