from typing import Any

import reflex as rx


def build_projetos_view(
    State,
    CARD_STYLE: dict[str, Any],
    custom_option_field,
    workflow_node,
    workflow_connection_line,
    pesquisa_builder_view,
) -> rx.Component:
    project_portfolio_panel = rx.vstack(
        rx.box(
            rx.vstack(
                rx.heading("Projeto Contratado", color="var(--text-primary)", size="4"),
                rx.text(
                    "Registre aqui qual serviço a SmartLab irá ofertar, para qual cliente e em que data o contrato entrou em execução.",
                    color="var(--text-muted)",
                ),
                rx.grid(
                    rx.input(
                        placeholder="Nome interno do projeto",
                        value=State.new_project_name,
                        on_change=State.set_new_project_name,
                        bg="var(--input-bg)",
                        color="var(--text-primary)",
                        width="100%",
                    ),
                    rx.select(
                        State.smartlab_service_options,
                        value=State.new_project_service_name,
                        on_change=State.set_new_project_service_name,
                        bg="var(--input-bg)",
                        color="var(--text-primary)",
                        width="100%",
                    ),
                    rx.cond(
                        State.new_project_service_name == "Outro",
                        custom_option_field(
                            "Novo Serviço SmartLab",
                            value=State.new_project_custom_service_name,
                            on_change=State.set_new_project_custom_service_name,
                            on_confirm=State.confirm_new_project_service_name,
                            placeholder="Digite aqui para cadastrar um novo serviço",
                            help_text="Clique em OK para registrar o serviço e trazê-lo de volta ao seletor.",
                        ),
                        rx.fragment(),
                    ),
                    rx.select(
                        State.project_client_options,
                        value=State.selected_project_client_option,
                        on_change=State.set_new_project_client_option,
                        placeholder="Cliente contratante",
                        bg="var(--input-bg)",
                        color="var(--text-primary)",
                        width="100%",
                    ),
                    rx.input(
                        type="date",
                        value=State.new_project_contracted_at,
                        on_change=State.set_new_project_contracted_at,
                        bg="var(--input-bg)",
                        color="var(--text-primary)",
                        width="100%",
                    ),
                    columns="2",
                    spacing="3",
                    width="100%",
                ),
                rx.button("Registrar Projeto", on_click=State.create_project, class_name="primary-soft-action"),
                align="start",
                spacing="3",
                width="100%",
            ),
            padding="1rem",
            width="100%",
            **CARD_STYLE,
        ),
        rx.box(
            rx.vstack(
                rx.hstack(
                    rx.heading("Portfólio de Projetos", color="var(--text-primary)", size="4"),
                    rx.spacer(),
                    rx.badge(State.selected_project_record["service_name"], color_scheme="purple"),
                    width="100%",
                ),
                rx.vstack(
                    rx.hstack(
                        rx.text("Todos os projetos", color="var(--text-primary)", font_weight="700"),
                        rx.spacer(),
                        rx.select(
                            State.project_portfolio_service_options,
                            value=State.project_portfolio_service_filter,
                            on_change=State.set_project_portfolio_service_filter,
                            bg="var(--input-bg)",
                            color="var(--text-primary)",
                            width="260px",
                        ),
                        rx.badge(f"{State.filtered_projects_data.length()} registros", color_scheme="gray", variant="soft"),
                        width="100%",
                        align="center",
                        spacing="3",
                    ),
                    rx.cond(
                        State.filtered_projects_data.length() == 0,
                        rx.box(
                            rx.text(
                                "Nenhum projeto encontrado para o serviço selecionado.",
                                color="var(--text-muted)",
                                font_size="0.86rem",
                            ),
                            width="100%",
                            padding="0.9rem 1rem",
                            border="1px dashed var(--input-border)",
                            border_radius="14px",
                            bg="var(--surface-soft)",
                        ),
                        rx.vstack(
                            rx.grid(
                                rx.text("ID", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", text_align="center", width="100%"),
                                rx.text("Projeto", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Serviço", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Cliente", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Data", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Entrevistas", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Status", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", width="100%"),
                                rx.text("Ações", color="var(--text-secondary)", font_weight="600", font_size="0.77rem", text_align="center", width="100%"),
                                grid_template_columns="60px minmax(220px,1.6fr) minmax(170px,1.15fr) minmax(140px,0.95fr) 118px 116px 110px minmax(220px,1.25fr)",
                                width="100%",
                                align_items="center",
                                justify_items="stretch",
                                padding="0.1rem 0 0.85rem",
                                border_bottom="1px solid rgba(148,163,184,0.18)",
                                column_gap="0.9rem",
                            ),
                            rx.foreach(
                                State.filtered_projects_data,
                                lambda item: rx.grid(
                                    rx.box(
                                        rx.text(item["id"], color="var(--text-primary)", font_weight="600", font_size="0.85rem"),
                                        width="100%",
                                        text_align="center",
                                    ),
                                    rx.cond(
                                        State.editing_project_id == item["id"].to_string(),
                                        rx.input(
                                            value=State.new_project_name,
                                            on_change=State.set_new_project_name,
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        rx.button(
                                            rx.text(item["name"], color="var(--text-primary)", font_weight="600"),
                                            on_click=State.select_project(f'{item["id"]} - {item["name"]}'),
                                            width="100%",
                                            justify_content="flex-start",
                                            text_align="left",
                                            bg="transparent",
                                            border="0",
                                            padding="0",
                                        ),
                                    ),
                                    rx.cond(
                                        State.editing_project_id == item["id"].to_string(),
                                        rx.select(
                                            State.smartlab_service_options,
                                            value=State.new_project_service_name,
                                            on_change=State.set_new_project_service_name,
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        rx.text(item["service_name"], color="var(--text-secondary)", font_size="0.82rem"),
                                    ),
                                    rx.cond(
                                        State.editing_project_id == item["id"].to_string(),
                                        rx.select(
                                            State.project_client_options,
                                            value=State.selected_project_client_option,
                                            on_change=State.set_new_project_client_option,
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        rx.text(item["client_name"], color="var(--text-secondary)", font_size="0.82rem"),
                                    ),
                                    rx.cond(
                                        State.editing_project_id == item["id"].to_string(),
                                        rx.input(
                                            type="date",
                                            value=State.new_project_contracted_at,
                                            on_change=State.set_new_project_contracted_at,
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        rx.text(item["contracted_at"], color="var(--text-secondary)", font_size="0.82rem"),
                                    ),
                                    rx.vstack(
                                        rx.text(item["interview_count"], color="var(--text-primary)", font_weight="600", font_size="0.83rem"),
                                        rx.text(
                                            f'Ações {item["action_count"]} • Workflow {item["workflow_count"]} • IA {item["knowledge_count"]}',
                                            color="var(--text-muted)",
                                            font_size="0.74rem",
                                            width="100%",
                                            white_space="normal",
                                            word_break="break-word",
                                        ),
                                        spacing="0",
                                        align="start",
                                        width="100%",
                                    ),
                                    rx.badge(item["status"], color_scheme="purple", variant="soft"),
                                    rx.cond(
                                        State.editing_project_id == item["id"].to_string(),
                                        rx.hstack(
                                            rx.button(
                                                "Salvar",
                                                on_click=State.save_project_inline,
                                                bg="rgba(34,197,94,0.16)",
                                                color="#86efac",
                                                border="1px solid rgba(34,197,94,0.34)",
                                                size="1",
                                            ),
                                            rx.button(
                                                "Cancelar",
                                                on_click=State.cancel_edit_project,
                                                bg="rgba(250,204,21,0.16)",
                                                color="#fde68a",
                                                border="1px solid rgba(250,204,21,0.34)",
                                                size="1",
                                            ),
                                            spacing="2",
                                            justify="center",
                                            width="100%",
                                        ),
                                        rx.hstack(
                                            rx.button(
                                                "Alterar",
                                                on_click=State.start_edit_project(item["id"]),
                                                bg="rgba(255,122,47,0.18)",
                                                color="#fdba74",
                                                border="1px solid rgba(255,122,47,0.38)",
                                                size="1",
                                            ),
                                            rx.button(
                                                "Excluir",
                                                on_click=State.request_delete_confirmation(
                                                    "project",
                                                    item["id"],
                                                    f'{item["name"]} | entrevistas {item["interview_count"]} | ações {item["action_count"]} | workflow {item["workflow_count"]} | IA {item["knowledge_count"]}',
                                                ),
                                                bg="rgba(239,68,68,0.2)",
                                                color="#fca5a5",
                                                border="1px solid rgba(239,68,68,0.4)",
                                                size="1",
                                            ),
                                            spacing="2",
                                            justify="center",
                                            width="100%",
                                        ),
                                    ),
                                    grid_template_columns="60px minmax(220px,1.6fr) minmax(170px,1.15fr) minmax(140px,0.95fr) 118px 116px 110px minmax(220px,1.25fr)",
                                    width="100%",
                                    align_items="center",
                                    justify_items="stretch",
                                    column_gap="0.9rem",
                                    padding="0.55rem 0",
                                    border_bottom="1px solid rgba(148,163,184,0.12)",
                                ),
                            ),
                            width="100%",
                            spacing="0",
                            align="stretch",
                        ),
                    ),
                    width="100%",
                    spacing="2",
                    align="start",
                ),
                align="start",
                spacing="3",
                width="100%",
            ),
            padding="1rem",
            width="100%",
            **CARD_STYLE,
        ),
        width="100%",
        spacing="4",
    )

    workflow_builder_panel = rx.box(
        rx.vstack(
            rx.hstack(
                rx.vstack(
                    rx.heading("Jornada Operacional do Projeto", color="var(--text-primary)", size="5"),
                    rx.text(
                        "A aba Workflow agora organiza a operacao do projeto em etapas de preparacao, execucao e fechamento. A ideia e preconfigurar o essencial e depois trabalhar apenas nas excecoes do projeto.",
                        color="var(--text-muted)",
                    ),
                    align="start",
                    spacing="1",
                    width="100%",
                ),
                rx.badge(State.selected_project_record["service_name"], color_scheme="purple", variant="soft"),
                width="100%",
                align="start",
                spacing="3",
            ),
            rx.box(
                rx.grid(
                    rx.box(
                        rx.vstack(
                            rx.text("Projeto", color="var(--text-muted)", font_size="0.78rem"),
                            rx.text(State.selected_project_record["name"], color="var(--text-primary)", font_weight="700"),
                            rx.text(State.selected_project_record["client_name"], color="var(--text-secondary)", font_size="0.82rem"),
                            align="start",
                            spacing="1",
                            width="100%",
                        ),
                        padding="0.8rem",
                        class_name="panel-card metric-card",
                        **CARD_STYLE,
                    ),
                    rx.foreach(
                        State.workflow_stage_summary,
                        lambda item: rx.box(
                            rx.vstack(
                                rx.text(item["label"], color="var(--text-muted)", font_size="0.78rem"),
                                rx.text(item["value"], color="var(--text-primary)", font_weight="700"),
                                rx.text(item["detail"], color="var(--text-secondary)", font_size="0.8rem"),
                                align="start",
                                spacing="1",
                                width="100%",
                            ),
                            padding="0.8rem",
                            class_name="panel-card metric-card",
                            **CARD_STYLE,
                        ),
                    ),
                    columns="5",
                    spacing="3",
                    width="100%",
                ),
                width="100%",
            ),
            rx.grid(
                rx.box(
                    rx.vstack(
                        rx.hstack(
                            rx.heading("Montar Jornada", color="var(--text-primary)", size="4"),
                            rx.spacer(),
                            rx.button(
                                "Carregar Jornada Sugerida",
                                on_click=State.seed_workflow_journey,
                                bg="rgba(255,122,47,0.18)",
                                color="#fdba74",
                                border="1px solid rgba(255,122,47,0.38)",
                                size="2",
                            ),
                            width="100%",
                            align="center",
                        ),
                        rx.text(
                            "Crie etapas com significado operacional. Use a jornada sugerida para partir de um baseline SmartLab e depois ajuste so o que for especifico do projeto.",
                            color="var(--text-muted)",
                            width="100%",
                        ),
                        rx.grid(
                            rx.input(
                                placeholder="Nome da etapa",
                                value=State.new_box_title,
                                on_change=State.set_new_box_title,
                                bg="var(--input-bg)",
                                color="var(--text-primary)",
                                width="100%",
                            ),
                            rx.select(
                                ["left", "center", "right"],
                                value=State.new_box_zone,
                                on_change=State.set_new_box_zone,
                                bg="var(--input-bg)",
                                color="var(--text-primary)",
                                width="100%",
                            ),
                            rx.select(
                                ["trigger", "etapa", "coleta", "analise", "relatorio"],
                                value=State.new_box_type,
                                on_change=State.set_new_box_type,
                                bg="var(--input-bg)",
                                color="var(--text-primary)",
                                width="100%",
                            ),
                            rx.input(
                                placeholder="Responsavel principal",
                                value=State.new_box_owner,
                                on_change=State.set_new_box_owner,
                                bg="var(--input-bg)",
                                color="var(--text-primary)",
                                width="100%",
                            ),
                            columns="2",
                            spacing="3",
                            width="100%",
                        ),
                        rx.text_area(
                            placeholder="Objetivo da etapa",
                            value=State.new_box_objective,
                            on_change=State.set_new_box_objective,
                            min_height="92px",
                            bg="var(--input-bg)",
                            color="var(--text-primary)",
                            width="100%",
                        ),
                        rx.grid(
                            rx.input(
                                placeholder="Gatilho para iniciar a etapa",
                                value=State.new_box_trigger,
                                on_change=State.set_new_box_trigger,
                                bg="var(--input-bg)",
                                color="var(--text-primary)",
                                width="100%",
                            ),
                            rx.input(
                                placeholder="Entrega esperada da etapa",
                                value=State.new_box_expected_output,
                                on_change=State.set_new_box_expected_output,
                                bg="var(--input-bg)",
                                color="var(--text-primary)",
                                width="100%",
                            ),
                            columns="2",
                            spacing="3",
                            width="100%",
                        ),
                        rx.hstack(
                            rx.button(
                                "Adicionar Etapa",
                                on_click=State.add_workflow_box,
                                bg="rgba(255,122,47,0.18)",
                                color="#fdba74",
                                border="1px solid rgba(255,122,47,0.38)",
                            ),
                            rx.button(
                                "Simular Jornada",
                                on_click=State.execute_workflow,
                                variant="ghost",
                                border="1px solid var(--input-border)",
                                color="var(--text-secondary)",
                            ),
                            rx.button(
                                "Limpar Registros",
                                on_click=State.clear_workflow_logs,
                                variant="ghost",
                                border="1px solid var(--input-border)",
                                color="var(--text-secondary)",
                            ),
                            width="100%",
                            spacing="3",
                            flex_wrap="wrap",
                        ),
                        spacing="3",
                        width="100%",
                        align="start",
                    ),
                    padding="1rem",
                    **CARD_STYLE,
                    width="100%",
                ),
                rx.box(
                    rx.vstack(
                        rx.heading("Etapas Sugeridas", color="var(--text-primary)", size="4"),
                        rx.text(
                            "Estas etapas ainda nao aparecem na jornada do projeto. Clique para trazer o baseline e depois refine as excecoes operacionais.",
                            color="var(--text-muted)",
                        ),
                        rx.cond(
                            State.workflow_missing_stage_templates.length() == 0,
                            rx.box(
                                rx.text("A jornada sugerida ja foi carregada integralmente.", color="var(--text-secondary)"),
                                width="100%",
                                padding="0.9rem 1rem",
                                border="1px dashed var(--input-border)",
                                border_radius="14px",
                                bg="var(--surface-soft)",
                            ),
                            rx.vstack(
                                rx.foreach(
                                    State.workflow_missing_stage_templates,
                                    lambda item: rx.box(
                                        rx.vstack(
                                            rx.hstack(
                                                rx.text(item["title"], color="var(--text-primary)", font_weight="700"),
                                                rx.spacer(),
                                                rx.badge(item["context"], color_scheme="orange", variant="soft"),
                                                width="100%",
                                                align="center",
                                            ),
                                            rx.text(item["objective"], color="var(--text-secondary)", font_size="0.82rem"),
                                            rx.text(f"Responsavel sugerido: {item['owner']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.text(f"Gatilho: {item['trigger']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.text(f"Entrega: {item['expected_output']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.button(
                                                "Adicionar a Jornada",
                                                on_click=State.add_workflow_stage_template(item["key"]),
                                                bg="rgba(255,122,47,0.18)",
                                                color="#fdba74",
                                                border="1px solid rgba(255,122,47,0.38)",
                                                size="1",
                                            ),
                                            align="start",
                                            spacing="2",
                                            width="100%",
                                        ),
                                        width="100%",
                                        padding="0.9rem",
                                        border="1px solid var(--input-border)",
                                        border_radius="14px",
                                        bg="var(--surface-soft)",
                                    ),
                                ),
                                width="100%",
                                spacing="3",
                                align="stretch",
                            ),
                        ),
                        spacing="3",
                        width="100%",
                        align="start",
                    ),
                    padding="1rem",
                    **CARD_STYLE,
                    width="100%",
                ),
                columns="2",
                spacing="4",
                width="100%",
            ),
            rx.box(
                rx.vstack(
                    rx.hstack(
                        rx.heading("Quadro da Jornada", color="var(--text-primary)", size="4"),
                        rx.spacer(),
                        rx.text(
                            "Preparacao, execucao e fechamento lado a lado para facilitar a leitura operacional do projeto.",
                            color="var(--text-muted)",
                            font_size="0.82rem",
                        ),
                        width="100%",
                        align="center",
                    ),
                    rx.grid(
                        rx.box(
                            rx.vstack(
                                rx.badge("Preparacao", color_scheme="blue", variant="soft"),
                                rx.foreach(
                                    State.workflow_left_stages,
                                    lambda item: rx.box(
                                        rx.vstack(
                                            rx.hstack(
                                                rx.text(item["title"], color="var(--text-primary)", font_weight="700"),
                                                rx.spacer(),
                                                rx.badge(item["stage_type_label"], color_scheme="gray", variant="soft"),
                                                width="100%",
                                                align="center",
                                            ),
                                            rx.text(item["objective"], color="var(--text-secondary)", font_size="0.82rem"),
                                            rx.text(f"Responsavel: {item['owner']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.text(f"Gatilho: {item['trigger']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.text(f"Entrega: {item['expected_output']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.hstack(
                                                rx.button("↑", on_click=State.move_workflow_box(item["id"], "up"), size="1", variant="ghost"),
                                                rx.button("↓", on_click=State.move_workflow_box(item["id"], "down"), size="1", variant="ghost"),
                                                rx.button("Execucao", on_click=State.drop_workflow_box_to_zone(item["id"], "center"), size="1", variant="ghost"),
                                                rx.button("Excluir", on_click=State.delete_workflow_box(item["id"]), size="1", color_scheme="red", variant="soft"),
                                                width="100%",
                                                spacing="2",
                                                flex_wrap="wrap",
                                            ),
                                            spacing="2",
                                            width="100%",
                                            align="start",
                                        ),
                                        width="100%",
                                        padding="0.9rem",
                                        border="1px solid var(--input-border)",
                                        border_radius="14px",
                                        bg="var(--surface-soft)",
                                    ),
                                ),
                                rx.cond(
                                    State.workflow_left_stages.length() == 0,
                                    rx.text("Nenhuma etapa nesta coluna.", color="var(--text-muted)", font_size="0.82rem"),
                                    rx.fragment(),
                                ),
                                width="100%",
                                spacing="3",
                                align="stretch",
                            ),
                            padding="1rem",
                            border="1px solid var(--input-border)",
                            border_radius="18px",
                            bg="rgba(59,130,246,0.06)",
                            width="100%",
                        ),
                        rx.box(
                            rx.vstack(
                                rx.badge("Execucao", color_scheme="orange", variant="soft"),
                                rx.foreach(
                                    State.workflow_center_stages,
                                    lambda item: rx.box(
                                        rx.vstack(
                                            rx.hstack(
                                                rx.text(item["title"], color="var(--text-primary)", font_weight="700"),
                                                rx.spacer(),
                                                rx.badge(item["stage_type_label"], color_scheme="gray", variant="soft"),
                                                width="100%",
                                                align="center",
                                            ),
                                            rx.text(item["objective"], color="var(--text-secondary)", font_size="0.82rem"),
                                            rx.text(f"Responsavel: {item['owner']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.text(f"Gatilho: {item['trigger']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.text(f"Entrega: {item['expected_output']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.hstack(
                                                rx.button("Preparacao", on_click=State.drop_workflow_box_to_zone(item["id"], "left"), size="1", variant="ghost"),
                                                rx.button("Fechamento", on_click=State.drop_workflow_box_to_zone(item["id"], "right"), size="1", variant="ghost"),
                                                rx.button("Excluir", on_click=State.delete_workflow_box(item["id"]), size="1", color_scheme="red", variant="soft"),
                                                width="100%",
                                                spacing="2",
                                                flex_wrap="wrap",
                                            ),
                                            spacing="2",
                                            width="100%",
                                            align="start",
                                        ),
                                        width="100%",
                                        padding="0.9rem",
                                        border="1px solid var(--input-border)",
                                        border_radius="14px",
                                        bg="var(--surface-soft)",
                                    ),
                                ),
                                rx.cond(
                                    State.workflow_center_stages.length() == 0,
                                    rx.text("Nenhuma etapa nesta coluna.", color="var(--text-muted)", font_size="0.82rem"),
                                    rx.fragment(),
                                ),
                                width="100%",
                                spacing="3",
                                align="stretch",
                            ),
                            padding="1rem",
                            border="1px solid var(--input-border)",
                            border_radius="18px",
                            bg="rgba(255,122,47,0.06)",
                            width="100%",
                        ),
                        rx.box(
                            rx.vstack(
                                rx.badge("Fechamento", color_scheme="green", variant="soft"),
                                rx.foreach(
                                    State.workflow_right_stages,
                                    lambda item: rx.box(
                                        rx.vstack(
                                            rx.hstack(
                                                rx.text(item["title"], color="var(--text-primary)", font_weight="700"),
                                                rx.spacer(),
                                                rx.badge(item["stage_type_label"], color_scheme="gray", variant="soft"),
                                                width="100%",
                                                align="center",
                                            ),
                                            rx.text(item["objective"], color="var(--text-secondary)", font_size="0.82rem"),
                                            rx.text(f"Responsavel: {item['owner']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.text(f"Gatilho: {item['trigger']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.text(f"Entrega: {item['expected_output']}", color="var(--text-muted)", font_size="0.78rem"),
                                            rx.hstack(
                                                rx.button("Execucao", on_click=State.drop_workflow_box_to_zone(item["id"], "center"), size="1", variant="ghost"),
                                                rx.button("Excluir", on_click=State.delete_workflow_box(item["id"]), size="1", color_scheme="red", variant="soft"),
                                                width="100%",
                                                spacing="2",
                                                flex_wrap="wrap",
                                            ),
                                            spacing="2",
                                            width="100%",
                                            align="start",
                                        ),
                                        width="100%",
                                        padding="0.9rem",
                                        border="1px solid var(--input-border)",
                                        border_radius="14px",
                                        bg="var(--surface-soft)",
                                    ),
                                ),
                                rx.cond(
                                    State.workflow_right_stages.length() == 0,
                                    rx.text("Nenhuma etapa nesta coluna.", color="var(--text-muted)", font_size="0.82rem"),
                                    rx.fragment(),
                                ),
                                width="100%",
                                spacing="3",
                                align="stretch",
                            ),
                            padding="1rem",
                            border="1px solid var(--input-border)",
                            border_radius="18px",
                            bg="rgba(34,197,94,0.06)",
                            width="100%",
                        ),
                        columns="3",
                        spacing="4",
                        width="100%",
                    ),
                    spacing="3",
                    width="100%",
                    align="stretch",
                ),
                padding="1rem",
                **CARD_STYLE,
                width="100%",
            ),
            rx.grid(
                rx.box(
                    rx.vstack(
                        rx.heading("Observacoes Operacionais", color="var(--text-primary)", size="4"),
                        rx.hstack(
                            rx.input(
                                placeholder="Registre observacoes, dependencias ou combinados do projeto",
                                value=State.new_sticky_note_text,
                                on_change=State.set_new_sticky_note_text,
                                bg="var(--input-bg)",
                                color="var(--text-primary)",
                                width="100%",
                            ),
                            rx.button(
                                "Adicionar Observacao",
                                on_click=State.add_sticky_note,
                                bg="rgba(255,122,47,0.18)",
                                color="#fdba74",
                                border="1px solid rgba(255,122,47,0.38)",
                            ),
                            width="100%",
                            spacing="3",
                        ),
                        rx.cond(
                            State.workflow_sticky_notes.length() == 0,
                            rx.text("Nenhuma observacao operacional registrada.", color="var(--text-muted)", font_size="0.82rem"),
                            rx.vstack(
                                rx.foreach(
                                    State.workflow_sticky_notes,
                                    lambda note: rx.box(
                                        rx.text(note["note"], color="var(--text-secondary)", font_size="0.82rem"),
                                        width="100%",
                                        padding="0.8rem",
                                        border="1px solid var(--input-border)",
                                        border_radius="12px",
                                        bg="var(--surface-soft)",
                                    ),
                                ),
                                width="100%",
                                spacing="2",
                                align="stretch",
                            ),
                        ),
                        spacing="3",
                        width="100%",
                        align="start",
                    ),
                    padding="1rem",
                    **CARD_STYLE,
                    width="100%",
                ),
                rx.box(
                    rx.vstack(
                        rx.heading("Registros da Simulacao", color="var(--text-primary)", size="4"),
                        rx.text(
                            "Use a simulacao para validar se a jornada faz sentido como sequencia operacional antes de partir para detalhes e automacoes futuras.",
                            color="var(--text-muted)",
                        ),
                        rx.cond(
                            State.workflow_logs.length() == 0,
                            rx.text("Nenhuma simulacao executada ainda.", color="var(--text-muted)", font_size="0.82rem"),
                            rx.vstack(
                                rx.foreach(
                                    State.workflow_logs,
                                    lambda line: rx.text(line, color="var(--text-secondary)", font_size="0.78rem"),
                                ),
                                width="100%",
                                spacing="1",
                                align="start",
                            ),
                        ),
                        spacing="3",
                        width="100%",
                        align="start",
                    ),
                    padding="1rem",
                    **CARD_STYLE,
                    width="100%",
                ),
                columns="2",
                spacing="4",
                width="100%",
            ),
            align="start",
            width="100%",
            spacing="4",
        ),
        padding="1rem",
        width="100%",
        min_width="100%",
        **CARD_STYLE,
    )

    return rx.vstack(
        rx.cond(
            State.can_configure_projects,
            rx.vstack(
                rx.box(
                    rx.vstack(
                        rx.hstack(
                            rx.heading("Projetos default", color="var(--text-primary)", size="5"),
                            rx.spacer(),
                            rx.hstack(
                                rx.foreach(
                                    State.project_admin_tabs,
                                    lambda tab: rx.button(
                                        rx.cond(
                                            tab == "cadastro",
                                            "Cadastro",
                                            rx.cond(tab == "projetos", "Projetos", "Workflow"),
                                        ),
                                        on_click=State.set_project_admin_tab(tab),
                                        bg=rx.cond(
                                            State.project_admin_tab == tab,
                                            "rgba(255,122,47,0.18)",
                                            "transparent",
                                        ),
                                        color=rx.cond(
                                            State.project_admin_tab == tab,
                                            "#fdba74",
                                            "var(--text-secondary)",
                                        ),
                                        border=rx.cond(
                                            State.project_admin_tab == tab,
                                            "1px solid rgba(255,122,47,0.38)",
                                            "1px solid var(--input-border)",
                                        ),
                                        size="2",
                                        width="100%",
                                        flex="1",
                                        justify_content="center",
                                    ),
                                ),
                                spacing="2",
                                width="100%",
                            ),
                            width="100%",
                            align="center",
                        ),
                        rx.box(
                            rx.cond(
                                State.project_admin_tab == "cadastro",
                                rx.vstack(
                                    rx.box(
                                        rx.vstack(
                                            rx.heading("Cadastro da Survey", color="var(--text-primary)", size="4"),
                                            rx.text(
                                                "Defina o serviço SmartLab, nome da pesquisa, dimensões e perguntas. Tudo fica vinculado à survey criada nesta aba.",
                                                color="var(--text-muted)",
                                            ),
                                            rx.hstack(
                                                rx.badge("Serviço SmartLab", color_scheme="orange"),
                                                rx.badge("Survey", color_scheme="purple"),
                                                rx.badge("Dimensões e Perguntas", color_scheme="gray"),
                                                spacing="2",
                                                width="100%",
                                                flex_wrap="wrap",
                                            ),
                                            align="start",
                                            width="100%",
                                            spacing="3",
                                        ),
                                        padding="1rem",
                                        width="100%",
                                        **CARD_STYLE,
                                    ),
                                    pesquisa_builder_view(),
                                    width="100%",
                                    min_width="100%",
                                    spacing="4",
                                ),
                                rx.cond(
                                    State.project_admin_tab == "projetos",
                                    project_portfolio_panel,
                                    rx.vstack(
                                        rx.select(
                                            State.project_id_options,
                                            value=State.selected_project_option,
                                            on_change=State.select_project,
                                            placeholder="Selecione projeto",
                                            bg="var(--input-bg)",
                                            color="var(--text-primary)",
                                            width="100%",
                                        ),
                                        workflow_builder_panel,
                                        width="100%",
                                        min_width="100%",
                                        spacing="4",
                                    ),
                                ),
                            ),
                            width="100%",
                            min_width="100%",
                            min_height="620px",
                        ),
                        width="100%",
                        min_width="100%",
                        spacing="3",
                        align="stretch",
                    ),
                    padding="1rem",
                    **CARD_STYLE,
                    width="100%",
                    min_width="100%",
                ),
                width="100%",
                min_width="100%",
                spacing="4",
                align="stretch",
            ),
            rx.box(
                rx.vstack(
                    rx.heading("Acesso restrito", color="var(--text-primary)", size="5"),
                    rx.text(
                        "A tela de Projetos e exclusiva do workspace default. Outros tenants nao acessam criacao, configuracao ou vinculacao de projetos.",
                        color="var(--text-muted)",
                    ),
                    align="start",
                    width="100%",
                    spacing="3",
                ),
                width="100%",
                padding="1rem",
                **CARD_STYLE,
            ),
        ),
        width="100%",
        spacing="4",
    )
